namespace ACBrBoleto.Core.Enums;

/// <summary>
/// Identifica o banco/tipo de cobrança. Corresponde a TACBrTipoCobranca no Delphi.
/// </summary>
public enum TipoCobranca
{
    Nenhum = 0,
    BancoDoBrasil,
    Santander,
    CaixaEconomica,
    CaixaSicob,
    Bradesco,
    Itau,
    BancoMercantil,
    Sicredi,
    Bancoob,
    Banrisul,
    Banestes,
    HSBC,
    BancoDoNordeste,
    BRB,
    BicBanco,
    BradescoSICOOB,
    BancoSafra,
    SafraBradesco,
    BancoCECRED,
    BancoDaAmazonia,
    BancoDoBrasilSICOOB,
    Uniprime,
    UnicredRS,
    Banese,
    CrediSIS,
    UnicredES,
    BancoCresolSCRS,
    CitiBank,
    BancoABCBrasil,
    Daycoval,
    UniprimeNortePR,
    BancoPine,
    BancoPineBradesco,
    UnicredSC,
    BancoAlfa,
    BancoDoBrasilAPI,
    BancoDoBrasilWS,
    BancoCresol,
    MoneyPlus,
    BancoC6,
    BancoRendimento,
    BancoInter,
    BancoSofisaSantander,
    BS2,
    PenseBankAPI,
    BTGPactual,
    BancoOriginal,
    BancoVotorantim,
    BancoPefisa,
    BancoFibra,
    BancoSofisaItau,
    BancoIndustrialBrasil,
    BancoAthenaBradesco,
    BancoQITechSCD,
    BancoUY3,
    BancoBocomBBM,
    BancoSicoob,
    BancoSisprime,
    BancoAilos,
    BancoCora,
    BancoSulcredi,
    BancoCredisan,
    BancoSofisa,
    BancoVortx,
    BancoAsaas,
    Kobana
}
